### ISSUE TITLE
Capturing environment of issue

### ISSUE THREAD

**Issue by muhammadaisaruddin** [cleaniquecoders/nadi-laravel#2]
**Is your feature request related to a problem? Please describe.**
Ability to capture application environment issue

**Describe the solution you'd like**
It would be wonderful if Nadi can capture most of the parameter in this sample screen. Take a look at environment tag
<img width="816" alt="image" src="https://github.com/cleaniquecoders/nadi-laravel/assets/46447781/0cfc0988-215a-4b16-b469-ef6dbf9ef17d">

**Describe alternatives you've considered**
Multiple tagging mechanism to issue created and can be filtered in the Issue Management screen

**Additional context**
Tagging with key:value, example environment:production

**Comment by nasrulhazim** [comment]
@muhammadaisaruddin kindly request the feature in [Nadi Issues](https://github.com/cleaniquecoders/nadi-issues/discussions/new?category=ideasl)
